controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ["f_left_wheel_joint", "b_left_wheel_joint"]
    right_wheel_names: ["f_right_wheel_joint", "b_right_wheel_joint"]

    wheel_separation: 0.58
    wheel_radius: 0.08

    use_stamped_vel: false

    odom_frame_id: odom

    enable_odom_tf: true

# joint_broad:
#   ros__parameters:
#     publish_rate: 50.0

#     use_local_topics: true